apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cwm-ingress
  namespace: cwmnamespace
  labels:
    app: cwm-ingress
    context: REnterprise
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "True" --> Does not work
    ingress.bluemix.net/redirect-to-https: "True"
    #ingress.bluemix.net/proxy-connct-timeout: "serviceName=cwm-rshiny-service timeout=32s"
    #ingress.bluemix.net/proxy-read-timeout: "serviceName=cwm-rshiny-service timeout=256s"
    #ingress.bluemix.net/keepalive-requests: "1024"
    #ingress.bluemix.net/keepalive-timeout:  "32"
    #ingress.bluemix.net/sticky-cookie-services: "serviceName=cwm-rshiny-service name=cwm-rshiny expires=1h path=/ hash=sha1"
    nginx.org/websocket-services: "cwm-rshiny-service"
  
spec:
  tls:
  - hosts:
    - rep-k8s-cluster.eu-de.containers.appdomain.cloud
    secretName: rep-k8s-cluster-48a40589c62cd829903b0d7849def5a2-0000
  rules:
  - host: rep-k8s-cluster.eu-de.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: cwm-rshiny-service
          servicePort: 3838

